import type { Idea } from '@/lib/types/idea';

/**
 * Export an idea as Markdown format.
 * Includes all required fields plus Source URL and Share URL.
 *
 * @param idea The idea to export
 * @param shareUrl The share URL for this idea
 * @returns Markdown-formatted string
 */
export function exportIdeaAsMarkdown(idea: Idea, shareUrl: string): string {
  const date = new Date(idea.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const sourceUrl = idea.provenance?.sourceUrl || 'Not available';

  return `# ${idea.name}

**Category:** ${idea.category}  
**ID:** ${idea.id}  
**Generated:** ${date}

## Concept

${idea.concept}

## The Gap

${idea.gap}

## The Fix

${idea.fix}

## Details

**Source URL:** ${sourceUrl}  
**Share URL:** ${shareUrl}

---

*Generated by IdeaPrinter*
`;
}

/**
 * Export an idea as plain text format.
 * Includes all required fields plus Source URL and Share URL.
 *
 * @param idea The idea to export
 * @param shareUrl The share URL for this idea
 * @returns Plain text formatted string
 */
export function exportIdeaAsText(idea: Idea, shareUrl: string): string {
  const date = new Date(idea.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const sourceUrl = idea.provenance?.sourceUrl || 'Not available';

  return `${idea.name}

Category: ${idea.category}
ID: ${idea.id}
Generated: ${date}

CONCEPT
${idea.concept}

THE GAP
${idea.gap}

THE FIX
${idea.fix}

DETAILS
Source URL: ${sourceUrl}
Share URL: ${shareUrl}

---
Generated by IdeaPrinter
`;
}
